### ISSUE TITLE
Support boosted chat effects

### ISSUE THREAD

**Issue by Latent-Logic** [zaytri/slime2#28]
For a long time twitch has had `Highlight My Message` / `;msg-id=highlighted-message;` available as a channel points redeem, and it would be nice to have that be able to add an effect to that highlighted message on stream. Further with the recent bit redeems there is now `Gigantify an Emote` and `Message Effects` which would also be fun to be able to have highlighted.

* Channel point redeem `Highlight My Message`
  * Identified by `msg-id=highlighted-message`
* Bits redeem `Gigantify an Emote`
  * Identified by `msg-id=gigantified-emote-message`
  * Note this can have text in addition to the giant emote, in which case the text is shown on the first line, then the emote is shown large directly below the text
* Bits redeem `Message Effects` has two sub-types
  * Identified by `msg-id=animated-message`
  * Sub-type glowy message has `animation-id=rainbow-eclipse`
  * Sub-type bounce emotes has `animation-id=simmer`
 
(As a note, the `On-Screen Celebration` bit redeem does not send any chat message that I've been able to see)

**Comment by zaytri** [comment]
Highlighted messages have been supported since the start, as seen here: https://docs.slime2.stream/twitch/message

For the other 2 you should be able to get that from the `tags` map within the `message` object.

**Comment by zaytri** [comment]
I won't be implementing official support for the new bits redeem message effects here, but I will ensure that they are included in the upcoming desktop app. In the meantime the `tags` map should be a viable workaround for your implementation needs.

**Comment by Latent-Logic** [comment]
Fair enough! This has given me enough information to explore tweaking the existing themes, I appreciate the doc link and the information about the tags being accessible as I wasn't aware of that.
